// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Apis\Templates\RestApiTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class RestApiTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Apis\Templates\RestApiTemplate.tt"
var model = (SmartAppInfo)Model;
            
            #line default
            #line hidden
            this.Write("import { create } from \'apisauce\';\n\nconst BASE_URL = \'https://api.github.com\';\nc" +
                    "onst TIMEOUT = 20000; //20 seconds\nconst TOKEN = \"abc\";\n\nexport default class Re" +
                    "st");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Apis\Templates\RestApiTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiSuffix));
            
            #line default
            #line hidden
            this.Write(@" {
  constructor() {
    const api = create({
      baseURL: BASE_URL,
      headers: { 'Accept': 'application/vnd.github.v3+json', Authorization: TOKEN },
      timeout: TIMEOUT
    });

    api.addAsyncRequestTransform(request => {
      return new Promise(resolve => setTimeout(resolve, TIMEOUT))
    })
  }

  async getAll(path) {
    return await api.get(path);
  }

  async get(path) {
    return await api.get(path);
  }

  async post(path, data) {
    return await api.post(path, data);
  }

  async put(path, data) {
    return await api.put(path, data);
  }

  async patch(path, data) {
    return await api.patch(path, data);
  }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
