// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\28Nov2018\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\AndroidTemplates\AndroidManifestTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class AndroidManifestTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 2 "D:\Working\Mobioos\Generators new changes\28Nov2018\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\AndroidTemplates\AndroidManifestTemplate.tt"

    var model = (SmartAppInfo)Model;

            
            #line default
            #line hidden
            this.Write("<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\r\n    package" +
                    "=\"com.");
            
            #line 6 "D:\Working\Mobioos\Generators new changes\28Nov2018\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\AndroidTemplates\AndroidManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write(@""">

    <uses-permission android:name=""android.permission.INTERNET"" />
    <uses-permission android:name=""android.permission.SYSTEM_ALERT_WINDOW""/>

    <application
      android:name="".MainApplication""
      android:label=""@string/app_name""
      android:icon=""@mipmap/ic_launcher""
      android:allowBackup=""false""
      android:theme=""@style/AppTheme"">
      <activity
        android:name="".MainActivity""
        android:label=""@string/app_name""
        android:configChanges=""keyboard|keyboardHidden|orientation|screenSize""
        android:windowSoftInputMode=""adjustResize"">
        <intent-filter>
            <action android:name=""android.intent.action.MAIN"" />
            <category android:name=""android.intent.category.LAUNCHER"" />
        </intent-filter>
      </activity>
      <activity android:name=""com.facebook.react.devsupport.DevSettingsActivity"" />
    </application>

</manifest>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
