// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\PackageJsonTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PackageJsonTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\PackageJsonTemplate.tt"

    var model = (SmartAppInfo)Model;

            
            #line default
            #line hidden
            this.Write("{\n  \"name\": \"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\PackageJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("\",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\PackageJsonTemplate.tt"

    if(model.Description != null)
    {

            
            #line default
            #line hidden
            this.Write("\n  \"description\": \"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\PackageJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Description));
            
            #line default
            #line hidden
            this.Write("\",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\PackageJsonTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write(@"
  ""version"": ""0.0.1"",
  ""private"": true,
  ""scripts"": {
    ""start"": ""node node_modules/react-native/local-cli/cli.js start"",
    ""test"": ""jest""
  },
  ""dependencies"": {
    ""apisauce"": ""^0.15.2"",
    ""prop-types"": ""^15.6.2"",
    ""react"": ""16.9.0"",
    ""react-native"": ""0.61.5"",
    ""react-native-i18n"": ""^2.0.12"",
    ""react-navigation"": ""^4.0.10"",
    ""react-navigation-stack"": ""^1.10.3"",
    ""react-native-gesture-handler"": ""^1.5.2"",
    ""react-redux"": ""^7.1.3"",
    ""redux"": ""^4.0.4"",
    ""redux-thunk"": ""^2.3.0""
  },
  ""devDependencies"": {
    ""@babel/core"": ""7.7.4"",
    ""@babel/runtime"": ""7.7.4"",
    ""@react-native-community/eslint-config"": ""0.0.5"",
    ""babel-jest"": ""24.9.0"",
    ""eslint"": ""6.7.1"",
    ""jest"": ""24.9.0"",
    ""metro-react-native-babel-preset"": ""0.56.3"",
    ""react-test-renderer"": ""16.9.0""
  },
  ""jest"": {
    ""preset"": ""react-native""
  }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
