// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DataModelTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    var model = (EntityInfo)Model;
     if(model.BaseEntity != null)
    {

            
            #line default
            #line hidden
            this.Write("import ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Extends.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            this.Write(" from \'./");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Extends.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\n\nexport default class ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(model.BaseEntity != null){
            
            #line default
            #line hidden
            this.Write(" extends ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Extends.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\n\n        constructor(\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    if(allProperties != null && allProperties.Count() > 0)
    {
    PropertyInfo last = allProperties.AsEnumerable().Last();
    foreach(PropertyInfo property in allProperties)
    {	
	 if (property.Equals(last))
     {

            
            #line default
            #line hidden
            this.Write("\n            ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("1\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\n            ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("1,\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

        }
	}
        }

            
            #line default
            #line hidden
            this.Write("\t\n        ){\t\n\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

      if(_superProperties != null && _superProperties.Count() > 0)
        {
		 PropertyInfo last = _superProperties.AsEnumerable().Last();

            
            #line default
            #line hidden
            this.Write("\n        super(\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

          foreach(var property in _superProperties)
          {
		  if (property.Equals(last))
          {

            
            #line default
            #line hidden
            this.Write("\n            ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("1\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

		  }
		 else
		 {

            
            #line default
            #line hidden
            this.Write("\n            ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("1,\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

        }
          }

            
            #line default
            #line hidden
            this.Write("\n        );\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

        }
     if (allProperties != null && allProperties.Count() > 0)
    {
        foreach(PropertyInfo property in allProperties)
        {
               if(!_superProperties.AsEnumerable().Contains(property))
                {

            
            #line default
            #line hidden
            this.Write("\n            this.");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("1;\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

               }
          }
       }

            
            #line default
            #line hidden
            this.Write("\n    }\n}\n\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
