// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class DataModelTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 2 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    var model = (EntityInfo)Model;

            
            #line default
            #line hidden
            
            #line 5 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
 
    if(model.BaseEntity != null)
    {

            
            #line default
            #line hidden
            this.Write("import ");
            
            #line 9 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(model.Extends)));
            
            #line default
            #line hidden
            
            #line 9 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            this.Write(" from \'./");
            
            #line 9 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(model.Extends)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 9 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix.ToLower()));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 10 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    }

            
            #line default
            #line hidden
            
            #line 13 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    foreach (ReferenceInfo reference in model.References.AsEnumerable())
    {

            
            #line default
            #line hidden
            this.Write("import ");
            
            #line 17 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Type));
            
            #line default
            #line hidden
            
            #line 17 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            this.Write(" from \'./");
            
            #line 17 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 17 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix.ToLower()));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 18 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\nexport default ");
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
 if (model.IsAbstract) {
            
            #line default
            #line hidden
            this.Write("abstract");
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("class ");
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(model.Id)));
            
            #line default
            #line hidden
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(model.BaseEntity != null){
            
            #line default
            #line hidden
            this.Write(" extends ");
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(model.Extends)));
            
            #line default
            #line hidden
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            
            #line 22 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\r\n\r\n    constructor(\r\n");
            
            #line 25 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    var count=model.AllProperties().Count(); 
    var counter = 0;
    foreach(var property in model.AllProperties())
    {
      if(counter<count-1)
      {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 33 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            this.Write("1,\r\n");
            
            #line 34 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

      }
      else
      {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            this.Write("1");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
if(model.References.Count() > 0){
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 40 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

      }
    counter++;
   }

    if(model.References.Count() > 0)
    {

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 49 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

        counter = 0;
        foreach (ReferenceInfo reference in model.References.AsEnumerable())
        {
            if(counter < model.References.Count() -1)
              {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 56 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Id));
            
            #line default
            #line hidden
            
            #line 56 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            this.Write("1,\r\n");
            
            #line 57 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

              }
              else
              {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 62 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Id));
            
            #line default
            #line hidden
            
            #line 62 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            this.Write("1\r\n");
            
            #line 63 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

            }
     counter++;
        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n    ){\r\n");
            
            #line 71 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    foreach(var property in model.AllProperties())
    {
        if(property.IsKey && model.BaseEntity != null)
        {

            
            #line default
            #line hidden
            this.Write("        super(\r\n");
            
            #line 78 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

            if(_superProperties.Count == 0)
            {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 82 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            this.Write("1\r\n");
            
            #line 83 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

            }
            else
            {
            counter = 0;
            foreach(var reference in _superProperties)
            {
                if(counter < _superProperties.Count -1)
                {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 93 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Id));
            
            #line default
            #line hidden
            this.Write("1,\r\n");
            
            #line 94 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 99 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Id));
            
            #line default
            #line hidden
            this.Write("1\r\n");
            
            #line 100 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

                }
                counter++;
            }
            }

            
            #line default
            #line hidden
            this.Write("        );\r\n\r\n");
            
            #line 108 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("        this.");
            
            #line 113 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 113 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id));
            
            #line default
            #line hidden
            this.Write("1;\r\n");
            
            #line 114 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

        }
    }

    foreach (ReferenceInfo reference in model.References.AsEnumerable())
    {

            
            #line default
            #line hidden
            this.Write("        this.");
            
            #line 121 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Id));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 121 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.Id));
            
            #line default
            #line hidden
            
            #line 121 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelsuffix));
            
            #line default
            #line hidden
            this.Write("1;\r\n");
            
            #line 122 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Models\Templates\DataModelTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
