// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ViewTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import React from \'react\';\nimport { \n  Text,\n  Button,\n  View,\n  ScrollView\n} fr" +
                    "om \'react-native\';\n\n// Styles\nimport styles from \'../Styles/StyleSheet\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

    if(apiIds.AsEnumerable() != null )
    {
    foreach(var api in apiIds.AsEnumerable())
        {  

            
            #line default
            #line hidden
            this.Write("\nimport * as ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(api.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions from \'../../Actions/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(api.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions\'; \n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

}
    }

            
            #line default
            #line hidden
            this.Write("\n\nexport default class ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Screen extends React.Component {\n    static navigationOptions = {\n        title:\'" +
                    "");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Title.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" Screen\'\n    };\n\n    constructor(props) {\n        super(props);\n    }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

  if(_layout.Actions.AsEnumerable() != null)
  {
    foreach(var action in _layout.Actions.AsEnumerable())
    {
         switch (action.Type.ToLower())
                {
                    case "navigation":
                        if(action.Target != null)
                        {
                            string[] actionTargetSplitted = action.Target.Split('.');
                            string targetedConcern = actionTargetSplitted[0].ToPascalCase();
                            string targetedLayout = actionTargetSplitted[1].ToPascalCase();

            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = () => {\n        this.props.on");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("();\n    }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                        }
                        break;
                    case "method":

            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = () => {\n        //TODO\n    }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                        break;
                    case "dataget": case "datalist": case "datacreate": case "dataupdate": case "datadelete":
                        if (action.Api != null && _api != null)
                        {
                            string[] actionSplitted = action.Api.Split('.');
                            string apiService = actionSplitted[0];
                            string apiAction = actionSplitted[1];

                            foreach (ApiInfo api in _api.AsEnumerable())
                            {
                                if (api.Id.ToLower().Equals(apiService.ToLower()) && api.Actions.AsEnumerable() != null)
                                {
                                    foreach (ApiActionInfo apiA in api.Actions.AsEnumerable())
                                    {
                                        if (apiA.Id.ToLower().Equals(apiAction.ToLower()))
                                        {

            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = (\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                            if (apiA.Parameters.AsEnumerable() != null && apiA.Parameters.AsEnumerable().Count() > 0)
                                            {
                                                ApiParameterInfo last = apiA.Parameters.AsEnumerable().Last();
                                                foreach (ApiParameterInfo apiParameter in apiA.Parameters.AsEnumerable())
                                                {
                                                    if (apiParameter.Id != null)
                                                    {
                                                       if (apiParameter.Equals(last))
                                                        {

            
            #line default
            #line hidden
            this.Write("\n        ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                                        }
                                                        else
                                                        {

            
            #line default
            #line hidden
            this.Write("\n        ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                                        }
                                                    }
                                                }
                                            }

            
            #line default
            #line hidden
            this.Write("\n    ) => {\n        ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(api.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions.");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiA.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                            if (apiA.Parameters.AsEnumerable() != null && apiA.Parameters.AsEnumerable().Count() > 0)
                                            {
                                                ApiParameterInfo last = apiA.Parameters.AsEnumerable().Last();
                                                foreach (ApiParameterInfo apiParameter in apiA.Parameters.AsEnumerable())
                                                {
                                                    if (apiParameter.Id != null && apiParameter.Equals(last))
                                                    {

            
            #line default
            #line hidden
            this.Write("\n            ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                                    }
                                                    else
                                                    {

            
            #line default
            #line hidden
            this.Write("\n            ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiParameter.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                                    }
                                                }
                                            }

            
            #line default
            #line hidden
            this.Write("\n        );\n    }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

                                        }
                                    }
                                }
                            }
                        }
                        break;
                }
        }
  }

            
            #line default
            #line hidden
            this.Write("\n    render() {\n        return (\n          <View style={styles.container}>\n      " +
                    "     <ScrollView>\n                <View>\n                   <Text>");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(_layout.Id.ToPascalCase())));
            
            #line default
            #line hidden
            this.Write("</Text>\n                </View>\n                <View>\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

    foreach(var action in _layout.Actions.AsEnumerable())
    {
        if(action.Type.ToLower().Equals("navigation"))
        {

            
            #line default
            #line hidden
            this.Write("\n                    <Button title=\"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(action.Id.ToPascalCase())));
            
            #line default
            #line hidden
            this.Write("\" onPress={this.");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("}/>\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\n                </View>\n                <View>\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

    foreach(var action in _layout.Actions.AsEnumerable())
    {
        if(action.Type.ToLower().Equals("method"))
        {

            
            #line default
            #line hidden
            this.Write("\n                    <Button title=\"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(action.Id.ToPascalCase())));
            
            #line default
            #line hidden
            this.Write("\" onPress={this.");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("}/>\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Views\Templates\ViewTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\n                </View>\n             </ScrollView>\n          </View>\n          )" +
                    ";\n    }\n}\n\n\n\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
