// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ContainerTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import React, { Component } from \'react\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    if(_layout != null && apiIds.AsEnumerable() != null && apiIds.AsEnumerable().Count() > 0 ){
     string apiId = apiIds.AsEnumerable().FirstOrDefault(); 

            
            #line default
            #line hidden
            this.Write("\nimport { connect } from \'react-redux\';\nimport { bindActionCreators } from \'redux" +
                    "\';\nimport * as ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiId.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions from \'../../Actions/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiId.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions\'; \nimport { withNavigation } from \'react-navigation\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\nimport  ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Screen  from \'../../Screens/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Screen\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    if(_layout != null)
    {

            
            #line default
            #line hidden
            this.Write("\n\nclass ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Container extends Component {\n\n    constructor(props) {\n        super(props);\n   " +
                    " }\n\n    componentDidMount() {\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    foreach(var action in _layout.Actions.AsEnumerable())
    {
        if(action.Type.ToLower().Equals("datalist"))
        {

            
            #line default
            #line hidden
            this.Write("\n        this.props.");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("();\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\n    }\n\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    if(_navigationActions != null && _navigationActions.Count() > 0)
    {
        foreach(var action in _layout.Actions.AsEnumerable())
        {
            if(action.Type.ToLower().Equals("navigation"))
            {
                string[] targetSplitted = action.Target.Split('.');

            
            #line default
            #line hidden
            this.Write("\n    on");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" = () => {\n        this.props.navigation.navigate(\'");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetSplitted[0].ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetSplitted[1].ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\');\n    }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("\n    render() {\n        if (this.props.hasErrored) {\n            return <p>Sorry!" +
                    " There was an error loading the items</p>;\n        }\n\n        if (this.props.isL" +
                    "oading) {\n            return <p>Loading…</p>;\n        }\n\n        return (\n      " +
                    "      <");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Screen items={this.props.data} \n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    if(_navigationActions != null && _navigationActions.Count() > 0)
    {
        foreach(var action in _layout.Actions.AsEnumerable())
        {
            if(action.Type.ToLower().Equals("navigation"))
            {

            
            #line default
            #line hidden
            this.Write("\n                on");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("={ this.on");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("\n            />\n        );\n  }\n}\n\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

    if(_layout != null && apiIds.AsEnumerable() != null && apiIds.AsEnumerable().Count() > 0 ){
     string apiId = apiIds.AsEnumerable().FirstOrDefault(); 

            
            #line default
            #line hidden
            this.Write(@"
const mapStateToProps = (state) => {
    return {
        data: state.data,
        hasErrored: state.itemsHasErrored,
        isLoading: state.itemsIsLoading
    };
};

const mapDispatchToProps = (dispatch) => {
    return {
        actions:bindActionCreators(");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiId.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions, dispatch)\n    };\n};\n\nexport default withNavigation(connect(mapStateToPro" +
                    "ps, mapDispatchToProps)(");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Container));\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

        }
        else{

            
            #line default
            #line hidden
            this.Write("\nexport default ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_layout.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Container;\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Containers\Templates\ContainerTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
