// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ReducersTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nimport initialState from \'../InitialState\';\r\n");
            
            #line 3 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
 
    if(_concern != null && _layout != null &&  _layout.Actions != null && _layout.Actions.Count > 0)
    {

            
            #line default
            #line hidden
            this.Write("import {\r\n");
            
            #line 8 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"

        foreach(ActionInfo action in _layout.Actions.AsEnumerable())
        {
            if (action.Id != null && action.Type != null)
            {
                if(!action.Type.ToLower().Equals("navigation"))
                {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 16 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 16 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_REQUEST,\r\n    ");
            
            #line 17 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 17 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_SUCCESS,\r\n    ");
            
            #line 18 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 18 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_FAILURE,\r\n");
            
            #line 19 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("} from \'../../Actions/");
            
            #line 24 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_concern.Id)));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 24 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_layout.Id)));
            
            #line default
            #line hidden
            this.Write("Actions\';\r\n\r\nexport default function ");
            
            #line 26 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(_layout.Id)));
            
            #line default
            #line hidden
            this.Write("Reducer(state = null, action) {\r\n    switch (action.type) {\r\n");
            
            #line 28 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"

        foreach(ActionInfo action in _layout.Actions.AsEnumerable())
        {
            if (action.Id != null && action.Type != null)
            {
                if(!action.Type.ToLower().Equals("navigation"))
                {

            
            #line default
            #line hidden
            this.Write("        case ");
            
            #line 36 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 36 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_REQUEST:\r\n            return action.isLoading;\r\n\r\n        case ");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_SUCCESS:\r\n            return[\r\n                ...state,\r\n                Object" +
                    ".assign({}, action.");
            
            #line 42 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(_layout.Id)));
            
            #line default
            #line hidden
            this.Write(")\r\n            ];\r\n\r\n        case ");
            
            #line 45 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concern.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 45 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_FAILURE:\r\n             return [\r\n                ...state,\r\n                Obje" +
                    "ct.assign({}, { isLoading: false }, action.error)\r\n            ];\r\n\r\n");
            
            #line 51 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("        default:\r\n            return state;\r\n    }\r\n}\r\n");
            
            #line 60 "D:\Working\Mobioos\Generators new changes\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Reducers\Templates\ReducersTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
