// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\28Nov2018\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\IosTemplates\Static\ContentsAppIconTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ContentsAppIconTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"{
  ""images"" : [
    {
      ""idiom"" : ""iphone"",
      ""size"" : ""29x29"",
      ""scale"" : ""2x""
    },
    {
      ""idiom"" : ""iphone"",
      ""size"" : ""29x29"",
      ""scale"" : ""3x""
    },
    {
      ""idiom"" : ""iphone"",
      ""size"" : ""40x40"",
      ""scale"" : ""2x""
    },
    {
      ""idiom"" : ""iphone"",
      ""size"" : ""40x40"",
      ""scale"" : ""3x""
    },
    {
      ""idiom"" : ""iphone"",
      ""size"" : ""60x60"",
      ""scale"" : ""2x""
    },
    {
      ""idiom"" : ""iphone"",
      ""size"" : ""60x60"",
      ""scale"" : ""3x""
    }
  ],
  ""info"" : {
    ""version"" : 1,
    ""author"" : ""xcode""
  }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
