// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\28Nov2018\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Common\Templates\IosTemplates\Static\InfoPlistTvOSTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class InfoPlistTvOSTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLI" +
                    "ST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\r\n<plist version=\"1" +
                    ".0\">\r\n<dict>\r\n\t<key>CFBundleDevelopmentRegion</key>\r\n\t<string>en</string>\r\n\t<key" +
                    ">CFBundleExecutable</key>\r\n\t<string>$(EXECUTABLE_NAME)</string>\r\n\t<key>CFBundleI" +
                    "dentifier</key>\r\n\t<string>org.reactjs.native.example.$(PRODUCT_NAME:rfc1034ident" +
                    "ifier)</string>\r\n\t<key>CFBundleInfoDictionaryVersion</key>\r\n\t<string>6.0</string" +
                    ">\r\n\t<key>CFBundleName</key>\r\n\t<string>$(PRODUCT_NAME)</string>\r\n\t<key>CFBundlePa" +
                    "ckageType</key>\r\n\t<string>APPL</string>\r\n\t<key>CFBundleShortVersionString</key>\r" +
                    "\n\t<string>1.0</string>\r\n\t<key>CFBundleSignature</key>\r\n\t<string>????</string>\r\n\t" +
                    "<key>CFBundleVersion</key>\r\n\t<string>1</string>\r\n\t<key>LSRequiresIPhoneOS</key>\r" +
                    "\n\t<true/>\r\n\t<key>UILaunchStoryboardName</key>\r\n\t<string>LaunchScreen</string>\r\n\t" +
                    "<key>UIRequiredDeviceCapabilities</key>\r\n\t<array>\r\n\t\t<string>armv7</string>\r\n\t</" +
                    "array>\r\n\t<key>UISupportedInterfaceOrientations</key>\r\n\t<array>\r\n\t\t<string>UIInte" +
                    "rfaceOrientationPortrait</string>\r\n\t\t<string>UIInterfaceOrientationLandscapeLeft" +
                    "</string>\r\n\t\t<string>UIInterfaceOrientationLandscapeRight</string>\r\n\t</array>\r\n\t" +
                    "<key>UIViewControllerBasedStatusBarAppearance</key>\r\n\t<false/>\r\n\t<key>NSLocation" +
                    "WhenInUseUsageDescription</key>\r\n\t<string></string>\r\n\t<key>NSAppTransportSecurit" +
                    "y</key>\r\n\t<!--See http://ste.vn/2015/06/10/configuring-app-transport-security-io" +
                    "s-9-osx-10-11/ -->\r\n\t<dict>\r\n\t\t<key>NSExceptionDomains</key>\r\n\t\t<dict>\r\n\t\t\t<key>" +
                    "localhost</key>\r\n\t\t\t<dict>\r\n\t\t\t\t<key>NSExceptionAllowsInsecureHTTPLoads</key>\r\n\t" +
                    "\t\t\t<true/>\r\n\t\t\t</dict>\r\n\t\t</dict>\r\n\t</dict>\r\n</dict>\r\n</plist>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
