// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AppMainStackNavigator : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    SmartAppInfo smartApp = (SmartAppInfo)Model;

            
            #line default
            #line hidden
            this.Write("import { createStackNavigator} from \'react-navigation-stack\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

if(smartApp != null && smartApp.Concerns != null && smartApp.Concerns.Count > 0)
{
    foreach(ConcernInfo concern in smartApp.Concerns)
    {

            
            #line default
            #line hidden
            this.Write("\nimport ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("StackNavigator from \'./");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("StackNavigator\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    }

            
            #line default
            #line hidden
            this.Write("\n\nexport default createStackNavigator({\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    foreach(ConcernInfo concern in smartApp.Concerns)
    {

            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concern.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("StackNavigator,\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    }

            
            #line default
            #line hidden
            this.Write("\n},\n  {\n    navigationOptions:{\n     headerStyle: {\n            backgroundColor: " +
                    "\'#f4511e\',\n        },\n        headerTintColor: \'#fff\',\n        headerTitleStyle:" +
                    " {\n            fontWeight: \'bold\',\n        }\n    }\n  }\n);\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
