// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Scaffold.Generators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class AppMainStackNavigator : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 1 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
SmartAppInfo smartApp = (SmartAppInfo)Model;
            
            #line default
            #line hidden
            this.Write("import { createStackNavigator} from \'react-navigation\';\r\n\r\n");
            
            #line 4 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

if(smartApp != null && smartApp.Concerns != null && smartApp.Concerns.Count > 0)
{
    foreach(ConcernInfo concern in smartApp.Concerns)
    {

            
            #line default
            #line hidden
            this.Write("import ");
            
            #line 10 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(concern.Id)));
            
            #line default
            #line hidden
            this.Write("StackNavigator from \'./");
            
            #line 10 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(concern.Id)));
            
            #line default
            #line hidden
            this.Write("StackNavigator\';\r\n");
            
            #line 11 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\nexport default createStackNavigator({\r\n");
            
            #line 16 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    foreach(ConcernInfo concern in smartApp.Concerns)
    {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 20 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(concern.Id)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 20 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(concern.Id)));
            
            #line default
            #line hidden
            this.Write("StackNavigator,\r\n");
            
            #line 21 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

    }

            
            #line default
            #line hidden
            this.Write("},\r\n  {\r\n    navigationOptions:{\r\n     headerStyle: {\r\n            backgroundColo" +
                    "r: \'#f4511e\',\r\n        },\r\n        headerTintColor: \'#fff\',\r\n        headerTitle" +
                    "Style: {\r\n            fontWeight: \'bold\',\r\n        }\r\n    }\r\n  }\r\n);\r\n");
            
            #line 37 "D:\01 Working\01 RedFabriq\01 working\generators\react-native\generator\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppMainStackNavigator.tt"

}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
