// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppNavigator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AppNavigator : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { createSwitchNavigator } from \'react-navigation\';\r\n\r\nimport AuthLoadingSc" +
                    "reen from \'../Screens/Auth/AuthLoadingScreen\';\r\nimport ");
            
            #line 5 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("StackNavigator from \'./");
            
            #line 5 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("StackNavigator\';\r\nimport AppMainStackNavigator from \'./AppMainStackNavigator\';\r\n\r" +
                    "\nexport default createSwitchNavigator({\r\n    AuthLoading: AuthLoadingScreen,\r\n  " +
                    "  Auth: ");
            
            #line 10 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AppNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("StackNavigator,\r\n    App: AppMainStackNavigator\r\n},\r\n  {\r\n    initialRouteName: \'" +
                    "AuthLoading\'\r\n  }\r\n);");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
