// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AuthStackNavigator : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { createStackNavigator } from \'react-navigation-stack\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"

    if(_rootScreen == string.Empty || _rootScreenFolder == string.Empty)
    {

            
            #line default
            #line hidden
            this.Write("\nimport MainScreen from \'../Screens/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreenFolder.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Screen\';\n\nconst AuthStackNavigator = createStackNavigator({\n    LoginMainScreen: " +
                    "MainScreen\n});\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("\nimport MainContainer from \'../Containers/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreenFolder.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_rootScreen.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Container\';\n\nconst AuthStackNavigator = createStackNavigator({\n    LoginMainScree" +
                    "n: MainContainer\n});\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\AuthStackNavigator.tt"

    }

            
            #line default
            #line hidden
            this.Write("\nexport default AuthStackNavigator;\n\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
