// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NavigationTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { createStackNavigator } from \'react-navigation-stack\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

if(_concernInfo != null)
{
    string concernId = _concernInfo.Id.ToPascalCase();
    if(_concernInfo.Layouts != null &&  _concernInfo.Layouts.Count > 0)
    {
        foreach(var layout in _concernInfo.Layouts)
        {
            string containerName = string.Format("{0}Container", layout.Id.ToPascalCase());
            //string navName = string.Format("{0}{1}", concernId, layout.Id.ToPascalCase());

            
            #line default
            #line hidden
            this.Write("\nimport ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write(" from \'../Containers/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concernInfo.Id));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\';\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\n\nconst ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concernInfo.Id));
            
            #line default
            #line hidden
            this.Write("StackNavigator = createStackNavigator({\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

    if(_concernInfo.Layouts != null &&  _concernInfo.Layouts.Count > 0)
    {
        foreach(var layout in _concernInfo.Layouts)
        {
            string containerName = string.Format("{0}Container", layout.Id.ToPascalCase());
             string navName = string.Format("{0}{1}", concernId, layout.Id.ToPascalCase());

            
            #line default
            #line hidden
            this.Write("\n        ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write(",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\n},\n{\n    navigationOptions: {\n        headerStyle: {\n            backgroundColor" +
                    ": \'#f4511e\',\n        },\n        headerTintColor: \'#fff\',\n        headerTitleStyl" +
                    "e: {\n            fontWeight: \'bold\',\n        }\n    }\n});\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\nexport default ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concernInfo.Id));
            
            #line default
            #line hidden
            this.Write("StackNavigator;");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
