// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class NavigationTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nimport { createStackNavigator } from \'react-navigation\';\r\n\r\n");
            
            #line 4 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

if(_concernInfo != null)
{
    string concernId = TextConverter.PascalCase(_concernInfo.Id);
    if(_concernInfo.Layouts != null &&  _concernInfo.Layouts.Count > 0)
    {
        foreach(var layout in _concernInfo.Layouts)
        {
            string containerName = string.Format("{0}Container", TextConverter.PascalCase(layout.Id));
            //string navName = string.Format("{0}{1}", concernId, TextConverter.PascalCase(layout.Id));

            
            #line default
            #line hidden
            this.Write("import ");
            
            #line 15 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write(" from \'../Containers/");
            
            #line 15 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concernInfo.Id));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 15 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 16 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\nexport default ");
            
            #line 21 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_concernInfo.Id));
            
            #line default
            #line hidden
            this.Write("StackNavigator = createStackNavigator({\r\n");
            
            #line 22 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

    if(_concernInfo.Layouts != null &&  _concernInfo.Layouts.Count > 0)
    {
        foreach(var layout in _concernInfo.Layouts)
        {
            string containerName = string.Format("{0}Container", TextConverter.PascalCase(layout.Id));
             string navName = string.Format("{0}{1}", concernId, TextConverter.PascalCase(layout.Id));

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 30 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 30 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 31 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("},\r\n{\r\n    navigationOptions: {\r\n        headerStyle: {\r\n            backgroundCo" +
                    "lor: \'#f4511e\',\r\n        },\r\n        headerTintColor: \'#fff\',\r\n        headerTit" +
                    "leStyle: {\r\n            fontWeight: \'bold\',\r\n        }\r\n    }\r\n});\r\n");
            
            #line 47 "D:\01 Working\01 RedFabriq\01 working\new_generators\React-Native\React-Native\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Navigation\Templates\NavigationTemplate.tt"

}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
