// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Frontend.ReactNative
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ActionsTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
 if(_api.Actions.AsEnumerable()!= null && _api.Actions.AsEnumerable().Count() > 0)
   {

            
            #line default
            #line hidden
            this.Write("import { ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiSuffix.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" } from \'../Api/");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiSuffix.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\';\n\n/**\n * Constants for action: ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiSuffix.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Actions\n*/\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"

        foreach(ApiActionInfo action in _api.Actions.AsEnumerable())
        {
            if (action.Id != null && action.Type != null)
            {

            
            #line default
            #line hidden
            this.Write("\n    const ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_REQUEST = \'");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_REQUEST1\';\n    const ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_SUCCESS = \'");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_SUCCESS1\';\n    const ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_FAILURE = \'");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_FAILURE1\';\n\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"

            }
        }

       foreach(ApiActionInfo action in _api.Actions.AsEnumerable())
       {
           if (action.Id != null && action.Type != null)
            {

            
            #line default
            #line hidden
            this.Write("\nexport function to");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("(){\n    return function(dispatch){\n        dispatch({ type:  ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_REQUEST, isLoading: true});\n\n        return ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiSuffix.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("()\n            .then(response => response.json())\n            .then(data =>{\n    " +
                    "            dispatch({ type: ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_SUCCESS, ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": data, isLoading: false });\n            })\n            .catch(error => {\n       " +
                    "         dispatch({ type: ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_api.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_FAILURE, error: error, isLoading: false });\n            });\n    };\n}\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-React-Native-master\GeneratorProject.ReactNative\GeneratorProject\Platforms\Frontend\ReactNative\Actions\Templates\ActionsTemplate.tt"

            }
       }
   }

            
            #line default
            #line hidden
            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
